steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - functions
    - deploy
    - hello_world1
    - --source=.
    - --trigger-http
    - --runtime=python37
    - --allow-unauthenticated
serviceAccount: hostproject-379219@appspot.gserviceaccount.com